# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'config.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui
from PySide.QtCore import SIGNAL

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Preferencias(QtGui.QDialog):
    def setupUi(self):
        self.setObjectName(_fromUtf8("Dialog"))
        self.resize(448, 492)
        self.tabWidget = QtGui.QTabWidget(self)
        self.tabWidget.setGeometry(QtCore.QRect(30, 20, 411, 461))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(20, 30, 181, 21))
        self.label.setStyleSheet(_fromUtf8("font: 75 12pt \"Bitstream Charter\";"))
        self.label.setObjectName(_fromUtf8("label"))
        self.comboBox = QtGui.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(210, 20, 41, 31))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(20, 70, 271, 21))
        self.label_3.setStyleSheet(_fromUtf8("font: 75 12pt \"Bitstream Charter\";"))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.toolButton = QtGui.QToolButton(self.tab)
        self.toolButton.setGeometry(QtCore.QRect(340, 70, 41, 21))
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(20, 90, 191, 21))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.pushButton = QtGui.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(140, 300, 131, 31))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 130, 381, 111))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.label_5 = QtGui.QLabel(self.groupBox_4)
        self.label_5.setGeometry(QtCore.QRect(10, 30, 141, 21))
        self.label_5.setStyleSheet(_fromUtf8("font: 75 12pt \"Bitstream Charter\";"))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.lineEdit_8 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_8.setGeometry(QtCore.QRect(150, 30, 211, 24))
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.label_12 = QtGui.QLabel(self.groupBox_4)
        self.label_12.setGeometry(QtCore.QRect(10, 60, 141, 21))
        self.label_12.setStyleSheet(_fromUtf8("font: 75 12pt \"Bitstream Charter\";"))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.lineEdit_7 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_7.setGeometry(QtCore.QRect(150, 60, 211, 24))
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox = QtGui.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 381, 131))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.lineEdit = QtGui.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(100, 40, 261, 24))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 40, 81, 21))
        self.label_6.setStyleSheet(_fromUtf8("font: 75 12pt \"Bitstream Charter\";"))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 80, 81, 21))
        self.label_7.setStyleSheet(_fromUtf8("font: 75 12pt \"Bitstream Charter\";"))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.lineEdit_2 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(100, 80, 261, 24))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 150, 381, 131))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.lineEdit_3 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(100, 40, 261, 24))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(10, 40, 81, 21))
        self.label_8.setStyleSheet(_fromUtf8("font: 75 12pt \"Bitstream Charter\";"))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(10, 80, 81, 21))
        self.label_9.setStyleSheet(_fromUtf8("font: 75 12pt \"Bitstream Charter\";"))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.lineEdit_4 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(100, 80, 261, 24))
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 290, 381, 131))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.lineEdit_5 = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_5.setGeometry(QtCore.QRect(100, 40, 261, 24))
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(10, 40, 81, 21))
        self.label_10.setStyleSheet(_fromUtf8("font: 75 12pt \"Bitstream Charter\";"))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(10, 80, 81, 21))
        self.label_11.setStyleSheet(_fromUtf8("font: 75 12pt \"Bitstream Charter\";"))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.lineEdit_6 = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_6.setGeometry(QtCore.QRect(100, 80, 261, 24))
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.pushButton.clicked.connect(self.SaveConfig)
        self.toolButton.clicked.connect(self.Ruta)


        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(self)

        self.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label.setText(_translate("Dialog", "Descargas simultaneas:", None))
        self.comboBox.setItemText(0, _translate("Dialog", "1", None))
        self.comboBox.setItemText(1, _translate("Dialog", "2", None))
        self.comboBox.setItemText(2, _translate("Dialog", "3", None))
        self.comboBox.setItemText(3, _translate("Dialog", "4", None))
        self.label_3.setText(_translate("Dialog", "Carpeta de descarga predeterminada:", None))
        self.toolButton.setText(_translate("Dialog", "...", None))
        self.label_4.setText(_translate("Dialog", "C:/user/data/Dowlaods", None))
        self.pushButton.setText(_translate("Dialog", "Guardar y Salir", None))
        self.groupBox_4.setTitle(_translate("Dialog", "Usuarios Gnu/Linux:", None))
        self.label_5.setText(_translate("Dialog", "Gestor de Archivos:", None))
        self.lineEdit_8.setText(_translate("Dialog", "ingrese el comando o ruta", None))
        self.label_12.setText(_translate("Dialog", "Gestor de Videos:", None))
        self.lineEdit_7.setText(_translate("Dialog", "ingrese el comando o ruta", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Ajustes", None))
        self.groupBox.setTitle(_translate("Dialog", "AnimeYT:", None))
        self.label_6.setText(_translate("Dialog", "User Agent:", None))
        self.label_7.setText(_translate("Dialog", "Cookies:", None))
        self.groupBox_2.setTitle(_translate("Dialog", "Jkanime:", None))
        self.label_8.setText(_translate("Dialog", "User Agent:", None))
        self.label_9.setText(_translate("Dialog", "Cookies:", None))
        self.groupBox_3.setTitle(_translate("Dialog", "animeflv:", None))
        self.label_10.setText(_translate("Dialog", "User Agent:", None))
        self.label_11.setText(_translate("Dialog", "Cookies:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "cookies cloudflare", None))
    
    def SaveConfig(self):
        self.emit(SIGNAL('SaveConfig'),self.comboBox.currentText())
        self.close()
    def Ruta(self):
        self.emit(SIGNAL('SelectCarpeta'))
